# In this Notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover
* Introductons to tensors
* Getting information from tensros
* Manipulating tensors
* Tensors & numpy
* Using @tf.function(a way to speed up your regular Python functions)
* Using GPUs with tensorFlow(or TPUs)
* Exercises to try for yourself! 

#Introduction to Tensors

In [2]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [10]:
#Create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [18]:
#Check the number of dimensions of tensorflow(ndim stands for number of tensorflow dimensions)
scalar.ndim

0

In [16]:
#Create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [19]:
#Check the dimensions of vector
vector.ndim

1

In [22]:
#Create a matrix(has more than 1 dimensions)
matrix = tf.constant([[10,10],[20,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 10]], dtype=int32)>

In [23]:
#Check the dimensions of matrix
matrix.ndim

2

In [24]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[2.,4.]],dtype=tf.float16) #Specify the data type with dtypr parameter
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 2.,  4.]], dtype=float16)>

In [25]:
another_matrix.ndim

2

In [27]:
#Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [28]:
tensor.ndim

3

What we've created so far:
* Scalar : a single number
* Vector : a number with direction(eg. wind speed and sirection)
* Matrix: a 2-dimensional array of numbers
* Tensor : an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional array is a vector)

###Creating tensors with 'tf.variable'

In [30]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [31]:
#Crete the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [32]:
#Let's try to change one of the elements in our changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [34]:
#How 'bout we try .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [35]:
#Let's try to change one of the elements in our unchangeable_tensor
unchangeable_tensor[0] = 7
unchangeable_tensor

TypeError: ignored

In [36]:
#How 'bout we try .assign()
unchangeable_tensor[0].assign(7) 

AttributeError: ignored

###Note: Rarely in practice will you need to decide whether to use 

---

tf.Variable or tf.constant to ceate tesnors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

###Creating random tensors

Random tensors are tensors of some arbitrary size which contains random numbers

In [40]:
#Create two random(but same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [41]:
#Are they equal?
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

###Shuffle the order of elements in a tensor

In [43]:
#Shuffle a tensor(value for when you want to shuffle your data so the inherent order doesn't efeect learning)
not_shuffled = tf.constant([[1,2],[5,3],[7,9]])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 3],
       [7, 9]], dtype=int32)>

In [55]:
#shuffle our non_shuffled data
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled) #Operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 3],
       [7, 9],
       [1, 2]], dtype=int32)>

####It looks like we want our shuffled tesnors to be in same order, we've got to use global level random seed as well as operational level random see.

###Other ways to Create tensors

In [57]:
#Create a tensor with all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [86]:
#Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Turn Numpy array into tensors
The main difference between Numpy array and TensorFlow tensors is that tensors can be run on a GPU(much faster for numerical computing).

In [62]:
#Turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #create a numpy array between 1 to 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [64]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

###Getting information from tensors
When dealing with tensors you probably want to be aware of the followings attributs:
* Shape
* Rank
* Axis or dimension
* Size

In [65]:
#Create a rank 4 tensor(4-dim)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [66]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [67]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [71]:
#Get various attributes of our tensor
print("Data type of every element", rank_4_tensor.dtype)
print("Number of dimensions(rank)", rank_4_tensor.ndim)
print("Shape of tensor", rank_4_tensor.shape)
print("Elements along the 0 axis", rank_4_tensor.shape[0])
print("Element salong the last axis", rank_4_tensor.shape[-1])
print("Total number of elements in our tesnors", tf.size(rank_4_tensor))
print("Total number of elements in our tesnors", tf.size(rank_4_tensor).numpy())

Data type of every element <dtype: 'float32'>
Number of dimensions(rank) 4
Shape of tensor (2, 3, 4, 5)
Elements along the 0 axis 2
Element salong the last axis 5
Total number of elements in our tesnors tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tesnors 120


###Indexing tensors
Tensor can be indexed just like Python lists.

In [72]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [73]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [74]:
#Create a rank 2 tensor(2-dim)
rank_2_tensor = tf.constant([[5,4],
                             [3,8]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [77]:
#Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8], dtype=int32)>

In [81]:
#Add an extra dimension to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [4]],

       [[3],
        [8]]], dtype=int32)>

In [82]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1 ) #-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [4]],

       [[3],
        [8]]], dtype=int32)>

In [83]:
tf.expand_dims(rank_2_tensor, axis = 0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 4],
        [3, 8]]], dtype=int32)>

In [84]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 4],
       [3, 8]], dtype=int32)>

##MAnipulating tensors(tensor operations)

**Basic Operations**

In [3]:
#You can add values to a tensor using addition operator
tensor = tf.constant([[10,7],[34,56]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [44, 66]], dtype=int32)>

In [4]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [34, 56]], dtype=int32)>

In [7]:
#Multiplication and substraction
tensor - 1
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [340, 560]], dtype=int32)>

In [11]:
#We can use tensorflow built-in functions too
tf.multiply(tensor,10)
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [44, 66]], dtype=int32)>

In [12]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [34, 56]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our matrix(or matrices) need to fulfil, if we are going to matrix multiply them:

1. The inner dimension must match
2. The resulting matrix has the shape of the outer matrix

In [13]:
#Matrix multiplication in tensor
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 338,  462],
       [2244, 3374]], dtype=int32)>

In [14]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 100,   49],
       [1156, 3136]], dtype=int32)>

In [15]:
#Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 338,  462],
       [2244, 3374]], dtype=int32)>

In [16]:
tensor.shape

TensorShape([2, 2])

In [17]:
#Create a tensor(3,2) 
X = tf.constant([[2,3],
                 [4,5],
                 [5,4]])
#Create another tensor(3,2) 
Y = tf.constant([[5,6],
                 [4,5],
                 [9,8]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5],
        [5, 4]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 6],
        [4, 5],
        [9, 8]], dtype=int32)>)

In [19]:
#Lets change the shape of Y
Y = tf.reshape(Y, shape=(2,3))

In [20]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25, 39, 32],
       [45, 69, 56],
       [45, 66, 52]], dtype=int32)>

In [21]:
#Change data type from float32 to float16(reduced precision)
B = tf.constant([1.7,4.6])
C = tf.constant([7,4])
D = tf.cast(B,dtype = tf.float16)

In [22]:
B.dtype, D.dtype

(tf.float32, tf.float16)

In [23]:
E = tf.cast(C, dtype=tf.float32)
C.dtype, E.dtype

(tf.int32, tf.float32)

###Aggregating tensors
Considering them from multiple values down to a smaller amount of values.

In [24]:
#Get the bsolute values
tf.abs(B)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 4.6], dtype=float32)>

###One hot-encoding tensors

In [2]:
#Create a list of indices
l = [0,1,2,3]

#One hot-encode our list
tf.one_hot(l,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [3]:
#Specify custom values for one-hot encoding
tf.one_hot(l,depth=4,on_value="I love deep learning", off_value="I also like dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I also like dance',
        b'I also like dance', b'I also like dance'],
       [b'I also like dance', b'I love deep learning',
        b'I also like dance', b'I also like dance'],
       [b'I also like dance', b'I also like dance',
        b'I love deep learning', b'I also like dance'],
       [b'I also like dance', b'I also like dance', b'I also like dance',
        b'I love deep learning']], dtype=object)>

###Finding access to GPUs

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Sun Feb 27 09:46:11 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    27W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

###Note: if you've access to a CUDA-enabled GPU, TensorFLow will automatically use it whenever possible.